### ISSUE TITLE
Its not isue.

### ISSUE THREAD

**Issue by harymk** [sweharris/Alexa-Smart-Home-VirtualButtons#1]
How to add devices

**Comment by sweharris** [comment]
The "usage" documentation has a section on creating buttons:  https://github.com/sweharris/Alexa-Smart-Home-VirtualButtons/blob/main/usage/README.md#createchange-button

**Comment by harymk** [comment]
Give me an example where am type this

**Comment by sweharris** [comment]
If you're using a command line with `curl` then the usage guide provides an example: `curl -H "Authorization: $PASS" $URL -d '{comamnd_you_want}'`

The install guide also shows how you can create buttons via the command line _or_ via the AWS console: https://github.com/sweharris/Alexa-Smart-Home-VirtualButtons/blob/main/install/README.md#via-the-api-preferred

In that example it was to set one of the "special" buttons, but you can do the same thing for normal buttons; just pick a number under 100 and it'll just work.

**Comment by harymk** [comment]
{"Answer:":"Bad JSON passed: invalid character 'c' looking for beginning of object key string"}curl: (3) [globbing] unmatched close brace/bracket in column 19

**Comment by harymk** [comment]
C:\Users\Home>curl -H "Authorization: pass" url/default/Smart_Home_Virtual_Buttons -d {"command":"setname","param1":"10", "param2":"Garage Door"}
{"Answer:":"Bad JSON passed: invalid character 'c' looking for beginning of object key string"}curl: (3) [globbing] unmatched close brace/bracket in column 19

**Comment by sweharris** [comment]
I don't know about Windows, but on Linux (which I use) I would surround the JSON with `'` characters.

So:

    curl -H "Authorization: pass" url/default/Smart_Home_Virtual_Buttons -d '{"command":"setname","param1":"10", "param2":"Garage Door"}'

Without them the spaces in the JSON would split the paramters and so the `-d` flag wouldn't send the whole string.

**Comment by harymk** [comment]
Which commant this. Put,post, request

**Comment by sweharris** [comment]
It's a POST; the `-d` on curl automatically sets that.

**Comment by harymk** [comment]
curl -H "Authorization: pass" url/default/Smart_Home_Virtual_Buttons -d "{\"command\":\"setname\", \"param1\":\"1\", \"param2\":\"Test Button 1\"}"

its worked

**Comment by harymk** [comment]
`curl -H "Authorization: pass" curl/default/Smart_Home_Virtual_Buttons -d "{\"command\":\"setname\", \"param1\":\"1\", \"param2\":\"Test Button 1\"}"`

its worked

**Comment by sweharris** [comment]
OK good.  Your \ quoting inside " maybe the best way to handle it in Windows, dunno. The result is the same as the Unix ' ... ' syntax.

Glad you got it working!

**Comment by harymk** [comment]
`{\"error\":\"\",\"error_description\":\"\",\"access_token\":\"Atza|IwEBIPfdoumj-e30VYKIJi2TW3JZo_kwtNP3an67la4DZGrm4rBZsyDsfRG3WQD7RaYpd_8gOKOZGfSTZeaIuIzZ9hOy1RjcMhQqdsioHSUasJxaKv6gY2DWPVEGj2ZmEj5NRJ2cogWf43RUzRrXNeE2iLaZsKpFkiPDkHEs3KqQ2-EnrBpUGNNFt1H5v0fhaLe3U5cbkw6Dkj_oLHwzmnn909A99j-mmeVSw0u6QhuY73co6410HDQcd4uCb6vSadeLXQYjBIWY1ZEutS6OW9Kpe5xa\",\"refresh_token\":\"Atzr|IwEBIIdS7aXiT7n4W3JsvESjcxsa3AKLVP1ffTsTETlNswFnWh6CyYEk7eksJ0WknBVfn3kNziqsGvvpKvpRe1-tNoiMYFC8Bq0l_DfXnc94Foon1lvtw5PF231vLO8Cr15J2FKtz20rSwHwALmKHu573JyXWxpDnnVs1ipv6S9NByj14UcPOZdhFMb0ffWUY_KA-v_bucvPaNqX8XzLbsbs4B1wo0MgIU9NEkEu1HxucYpSUZdQDd7FDsZtYxxZrccZh9t5VWs5nVt6D6jYH-NSfawi\",\"expires_in\":3600,\"TimeSet\":1620265649}`

**Comment by sweharris** [comment]
What command did you run that caused that error?  This looks like the notification secret that's used to tell Alexa when a button has been pressed.  I'm not sure what command path you used to get that response.

**Comment by harymk** [comment]
Linked to alexa skill

**Comment by harymk** [comment]
100001 in db showing this

**Comment by sweharris** [comment]
Oh, OK.  That's not a problem.  That's saying there's no error; error: "", error_description: "", access_token: "secret.."... and so on.

That's a good sign.  It means the linking worked correctly.

**Comment by harymk** [comment]
Ok. device not discovered

**Comment by sweharris** [comment]
Give it 5 minutes.  I've noticed Alexa doesn't always populate new devices immediately!

**Comment by harymk** [comment]
ok

**Comment by harymk** [comment]
one more is this suport colour command, fan speed

**Comment by sweharris** [comment]
No, this emulates a door sensor; Alexa only supports "open" or "closed".   Sensors (door or motion) are the only ones that can be used to trigger routines, so more other devices like coloured lights or fans can't be emulated and still be used to trigger routines.

**Comment by harymk** [comment]
why try that too...

**Comment by sweharris** [comment]
By mistake when I was writing this code I did emulate a smart switch.  It showed up in the devices, but didn't show up in the triggers for a routine.  I dug deeper into the Alexa documentation and found it was only sensors (door, motion) that can be used as a smart home trigger for routines.   Since this program's goal was to allow for routines to be triggered I had to emulate a sensor.

**Comment by harymk** [comment]
ok
