### ISSUE TITLE
Extra config step needed to fix Invalid Server Error

### ISSUE THREAD

**Issue by bmccluskey** [sweharris/Alexa-Smart-Home-VirtualButtons#4]
Hi 
Thanks for the great work.  However, I think something has changed and there is another setting that needs to be configured. It took me a couple of days of fiddling to sort it out. 

Every time, I tried an API call the result was being returned as 500 Internal Server Error.
When I examined the logs, the lambda function was working correctly and I could see the result in the logs it was attempting to send was correct. I also had success with the Alexa integration, all was working as expected.

Under the Smart Home Virtual Buttons API, Integrations Tab, Press Manage Integrations and then Press Edit. Expand Advanced Settings and change the Payload Format Version from 1.0 to 2.0 and press Save. See the picture below.  Once I did this the API started returning the correct results.  I initially set up on eu-west-1 but then replicated it on us-east-1, identical results. 1.0 seems to be the default payload format.

![image](https://github.com/sweharris/Alexa-Smart-Home-VirtualButtons/assets/19671956/c8bce7a2-c166-4ca8-90ed-c184b7cc0c77)

**Comment by sweharris** [comment]
Oh that's interesting.  I wonder if this is what #3 was also trying to report, but the issue got closed by the reporter without resolution.  I thought I'd created a resulting JSON to handle both v1 and v2 (which my install defaulted to; huh) but not being able to test it myself I couldn't validate.

This is great feedback, thanks.  I'll update the install guide to note this.  Making sure everyone is on v2 is a good idea.

**Comment by sweharris** [comment]
Following added to the install documentation

_Now for a sanity check, we need to ensure the API version is set to version 2.0. In my deployments it was that, but others have reported it defaults to 1.0. Maybe something changed in the trigger setup..._

_So from the lambda overview, click on the API Gateway and select the API trigger. This will take you to the "API Gateway" configuration page. On the left menu select "Integrations", and then select the "ANY" route. You will now see a "Payload format version" definition. If it says 1.0 then edit the setting ("manage"/"edit"/"advanced") and change it to 2.0._

Thanks!
