### ISSUE TITLE
Unable to link the skill at this time.

### ISSUE THREAD

**Issue by mocallins** [sweharris/Alexa-Smart-Home-VirtualButtons#7]
I was going to compliment your instructions, until i got to the point of enabling the skill, lol.

All in all, though, with all the complicated info to put in, not bad at all, however,lol

But i may have done it to myself, not completely sure, I think i may have screwed up at the "Scope, add a scope step, Create a skill>Account Linking>add a scope value "profile:user_id"
I wan't paying close enough attention and i replaced the vault that was listed, with the "profile..."
Don't know if that's important, but i can't seem the find that default value to put back in.

Another qusetion, hoiw many "buttons" should i be able to create, after this setup ?
Using the cmdline on the linux box i was probably going to use these on, i could only get it to crewted 2, weird, however i didn't/don't know if that has to do with the "setting security on the API"

Any help would be greatly appreciated

**Comment by sweharris** [comment]
There is no default value for "scope" (at least there wasn't when I set mine up).  So it should just say "profile:user_id" for scope and nothing else.

If you're getting "unable to link" errors then you need to check all the magic numbers; just one mistake anywhere in this horrible complicated process is enough to cause an error.  It's very easy to get wrong (last time I built a test instance I skilled a step! oops!) and whitespace is important (it can look right on the screen but an extra space can break things).  So triple check :-)

The code should be able to handle 99,999  buttons but I really don't know how far Alexa itself would scale.  I suspect something internal to Amazon would break if you tried that!  I have 6 buttons defined, myself.
```
% ./bootstrap -command getbuttons   
     1 OFF Test Button
    10 OFF Garage Button
    11 OFF Washer Button
    12 OFF Drier Button
    13 OFF Front Door
    14 OFF Back Door
```

**Comment by mocallins** [comment]
Well in thinking about asking another question, i went and tried to copy down all the magic numbers, since i think you'd probably ask if i had them, and i would have normally said, i just capture them off the different pages.
Which now i think i probably don't have them all correctly.
My question was going to be are there 2 different client id and client secret, 1 from amazon, and 1 from Alexa developer.
And since you have them both in the magic numbers list, i'm thinking they are different.
So if you can guide me where i can capture those numbers it would be a great help.

**Comment by sweharris** [comment]
Yes, the "Login with Amazon" client ID/secret and the Alexa client ID/secret are different.  

There's a file called `Numbers.txt` in the `install` documentation directory.   You should fill this out as you go through the install process.  Don't share these numbers with anyone, but save a copy so you have them if you need them.

You can also go back into the various pages and get them all again, but that's a lot of places to look, which is why I use the `Numbers.txt` file :-)

**Comment by mocallins** [comment]
Yep just capturing them now.
Oddly, or by design, idk, in configuring the account linking, does the cleint secret always have to be filled in, or should it be saved, when pressing the saved button ?

**Comment by sweharris** [comment]
So the way it works is you go to "login with Amazon" and that _generates_ a client ID and secret, and then you go to the Alexa Developer portal and you _enter_ both of these values into the ACCOUNT LINKING tab.   This is how the Alexa backend is able to access your data.

Similarly when you go to the Alexa skill you _generate_ an ID and secret, and these get entered into the application with the "setclientid" and "setclientsecret" code.  This allows this code to talk to Alexa.  

So you can think of the ID/secret as a username/password to let the different parts of the system (skill, Alexa, Amazon) all talk to each other.

So when it asks you to enter an ID and secret you _must_ enter both.

**Comment by mocallins** [comment]
Do these look right ?


![image](https://github.com/user-attachments/assets/f901b117-011b-434d-9746-0ef03b36aeeb)

**Comment by mocallins** [comment]
And this ?

![image](https://github.com/user-attachments/assets/ba5294ce-aa64-4ddb-b47a-f413706f1adf)

**Comment by sweharris** [comment]
They _seem_ OK, but all the numbers are unique to you so I don't know if they're right or not.  You need to enter the Login with Amazon client secret here.

**Comment by mocallins** [comment]
> They _seem_ OK, but all the numbers are unique to you so I don't know if they're right or not. You need to enter the Login with Amazon client secret here.

Yes i do that, but every time i come to this screen its empty

**Comment by mocallins** [comment]
Is the default endpoint, the same as one of the redirect urls ?

**Comment by sweharris** [comment]
As long as you've entered it correctly, that's fine.

The default endpoint is the arn that you've already good.  The redirect URLs are part of how the backend authentication works and is totally different.

**Comment by mocallins** [comment]
So i'm thinking all the backend nuts and bolts to create buttons is working, because i can use the API to create/delete them. I have no doubt setting the state would all work correctly, because the API is working.

It seems kind of awkward that i have to link to my own _widgtes_, that only i can see.
Now if i were going to use yours, that would be a different issue.

Has anybody else deployed this and got it all working ?

**Comment by sweharris** [comment]
The http API side of things doesn't talk to Alexa, so that bit will work even if the secrets are wrong.

For me to host a service that other people could use would require an even more complicated setup (a full Oauth setup, a web site, a different data model) _and_ I'd need to get the skill certified by Amazon to publish it.  It'd probably end up costing money to run, so would then require a subscription and... yeah, no.  I'm not doing that!  If you want a commercial offering then I linked to a  couple in the readme.

Yes, other people have got this working; for example here's 2 people - https://github.com/sweharris/Alexa-Smart-Home-VirtualButtons/issues/6

**Comment by mocallins** [comment]
> Do these look right ?
> 
> ![image](https://private-user-images.githubusercontent.com/1242690/358023249-f901b117-011b-434d-9746-0ef03b36aeeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDQ5NzQsIm5iZiI6MTcyMzc0NDY3NCwicGF0aCI6Ii8xMjQyNjkwLzM1ODAyMzI0OS1mOTAxYjExNy0wMTFiLTQzNGQtOTc0Ni0wZWYwM2IzNmFlZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTc1NzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI2MDg2NWM2NmNjYjJlNGIyZjRlODY4NzU4N2E0MDA4NzYxNGYxNTFkYjM4MjBiOWQxYWUzNjBlOTU2ZWFlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fGLT8l4udV7WDcY2julzyFCO4LyyHSiVsxGX0GtUaz4)

So on this page do i need to have entries in the 3 checkboxes  at the bottom ?

**Comment by sweharris** [comment]
Image not found; did you delete it?

**Comment by mocallins** [comment]
> Image not found; did you delete it?

No i just did a quote reply, it was the first image i uploaded.

**Comment by mocallins** [comment]
Well just poking around i got it to link.

I don't know which one fixed it buuuttttt,lol

I turned off the , or moved the slider for "_Send Alexa Event_s" In the Aleca Developer console>Build

And i entered a value of 10 in the _Default Access Token Expiration Time_, on the account linking tab

So in my Alexa device, since i just defined it with the API and didn't specify what kind of a button it was, the setup see's it as a sensor ?

**Comment by sweharris** [comment]
The buttons show up as contact sensors; yes.  For Alexa they have "open" and "closed" states.  I cheat and pretend they're buttons that can be pushed :-)

The `jq` command is a good way of parsing JSON output, but my API response is always `{"Answer":"sometext"}` so you could use `sed` or anything else to process it!

If you set up `~/.aws/credentials` with an access key and a secret key  (see the AWS documentation on how to do this; it's standard AWS cloud stuff) then you can even use the CLI directly and the output will be plain text

eg
```
% ./bootstrap -command getbuttons    
    10 OFF Garage Button
    11 OFF Washer Button
    12 OFF Drier Button
    13 OFF Front Door
    14 OFF Back Door
```

**Comment by mocallins** [comment]
Do you want me to go ahead and close this issue, since i can now do all the things with buttons via the API calls, and I can verify the sensor is actually changing state in my Alexa device ?
Because even though i can verify the state changing, i actually created some routines to react to the events, but the routine is not getting triggered  :(

**Comment by sweharris** [comment]
Did you turn back on "send alexa events" ?  With that off it will prevent the skill from letting Alexa know immediately when a change occured.  It's possible that routine triggering  requires the change event to be sent, rather than depending on a discovery detecting the state change.

But yes, since you've successfully linked, I'll close this.

**Comment by mocallins** [comment]
> Did you turn back on "send alexa events" ? With that off it will prevent the skill from letting Alexa know immediately when a change occured. It's possible that routine triggering requires the change event to be sent, rather than depending on a discovery detecting the state change.
> 
> But yes, since you've successfully linked, I'll close this.

Yes i did turn back on  "send alexa events" and i've gone in and verified that it is still on.
I'm assuming that is working, because when i look at the sensor / button in the Alexa app on my device, i can see that the state changes.

**Comment by sweharris** [comment]
Unfortunately when you have the app open and looking at a device then it starts to poll every few seconds, so you see a state change but it doesn't mean the event got sent.
