### ISSUE TITLE
Is the discovery up to date?

### ISSUE THREAD

**Issue by nickrmb** [sweharris/Alexa-Smart-Home-VirtualButtons#8]
So I created a button a while ago and as far as I remember it was automatically discovered by Alexa.
Now I created a second and a third button, but they do not show up in the Alexa app.
Even after trying to discover them using different ways I was not able to find them.

They definitely exist as the command "getbuttons" returns the following ones:
{
  "Answer:": "     1 ON Washer\n     2 OFF Window\n     3 ON Garage\n"
}

Is there any ideal way to discover them or any additional steps I have overseen?

**Comment by nickrmb** [comment]
For me it also seems like the device is discovered, at least the Alexa.Discovery response includes all 3 buttons that I defined:

[json.json](https://github.com/user-attachments/files/16659104/json.json)

Still no new devices show up in the alexa app when I ask "alexa, discover new devices". Even after multiple days. Do you have an idea how I could further debug the problem or am I missing something?

**Comment by sweharris** [comment]
The logs contain all the communication between Alexa and the code.  Hmm.

Did you deploy to the right region?  I wouldn't have thought this would have caused this behaviour, but who knows what Amazon have done.

It might be worth pressing one of the buttons to see if a "state change" message causes the button to be found.

**Comment by nickrmb** [comment]
I have now redone the tutorial as I have also seen that I forked a while ago and it was not the newest version.
Now, I was able to link the skill and I also got logs for that in CloudWatch.
But every time I try discovery in the app nothing shows up in CloudWatch, seeming like the request does not even get that far.
Therefore I am confused, as the skill should be linked to the lambda function but where are the discovery requests?

**Comment by sweharris** [comment]
I know this may be a silly question, but did you refresh the cloudwatch page?  New log streams don't automatically show up and you may need to reload the page.  Or, if the entry is recent enough, it may hid in the existing logstream and not create a new one.

Whenever Alexa calls the skill the very first thing that will be printed is "Handler started", followed by "incoming data" and then a determination if this was an API call or an Alexa call
eg
![image](https://github.com/user-attachments/assets/8ddfaba3-6be2-4cfc-8d46-b4676823be65)

If you're not seeing this then the Alexa backend isn't calling your routine.  But it must have done it in the past if you're seeing the Alexa call to link the skill and saw the "Attempting to get tokens for code" log entry.

Where are you based and what region did you deploy in?

**Comment by nickrmb** [comment]
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/25d0b7e6-3ecb-44e9-8443-d97f16c0b614">

This is the last log entry I got, it is the one where I linked the account in the alexa app to activate the skill. I have asked "alexa, discover new devices" since then multiple times, also refreshed the page, no new logs.

I am based in Germany and use the ireland (eu-west-1) region.

What I am curious is that this message still shows up in the skill:
<img width="871" alt="image" src="https://github.com/user-attachments/assets/1fe7ad53-a373-482c-a47b-27d97190841c">

Even though I already linked my account (also redirect urls are correct):
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/263ad078-9d7f-4728-b75f-57714bcd2dad">
The secret always disappears after I refresh the page (and also saved before!), but I guess this is an intentional security feature by amazon.

**Comment by sweharris** [comment]
Hmm, that's a good successful link because we get an access token back (which you should be able to see in dynamodb slot 100001, or via the undocumented API call "getbuttonsall").

I also  see the "You will need to configure..." line in the developer console; I think it's a generic message; I ignore it :-)

Hmm, the default endpoint ARN would appear to be correct because otherwise the linking wouldn't have worked!

eu-west-1 is correct.

Hmm.

When you say you refreshed the page, did you refresh the page you pasted above, or did you refresh the previous page?   This page 
![image](https://github.com/user-attachments/assets/e579b2c7-a9a3-4565-96cf-fdc5c558309d)

That's because new log messages may (probably will) show in a new log stream, rather than appending to the existing one.

You can also make an API call and that will generate log messages.

**Comment by nickrmb** [comment]
The one in the screenshot, refreshed the page as well as used the refresh button. Neither show new log entries. I think its not a log issue, as no devices are discovered as well.

**Comment by sweharris** [comment]
Make an API call and verify log entries are being generated.  Calling "getbuttons" would be sufficient.  You should then see something like
![image](https://github.com/user-attachments/assets/7e1c17aa-23d2-4c96-a947-2da73a05c3ab)

If you don't see this then logging is broken somewhere and you should verify that part of the config.

**Comment by nickrmb** [comment]
Yep, got a new one instantly
<img width="1157" alt="image" src="https://github.com/user-attachments/assets/30ef01ee-cd30-4f7c-bb13-62cb0b5b73f8">

**Comment by sweharris** [comment]
Very odd.  At this point I'd double check the ARN for the skill is still correct, just in case it got changed and that you haven't accidentally clicked any of the "region" endpoints.  Also re-enter the client id/secret (ensuring no hidden spaces) just in case.   We know this  previously worked 'cos otherwise the linking call wouldn't have been seen!

Also (and this _shouldn't_ make a difference, but I've seen Alexa backend is properly normalised) try doing a discovery from the app rather than by voice.

No new logs means the lamba isn't even being called!

**Comment by nickrmb** [comment]
I relinked the device (disabled skill, enabled the skill to link again), got a log instantly:
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/93472d2d-4dc6-48e8-ab29-c7473f94c18f">
So I am very certain that the ARN in the skill is defined properly. Also the client and secret should be defined properly (as it should not work without it?).

Afterwards alexa started device discovery automatically, but no log appeared for that.
Also did manual alexa discovery, i chose "other" and then "wlan", but I am not certain that this is the correct choice.

Also this is enabled, which should forward all requests to lambda (?):
<img width="942" alt="image" src="https://github.com/user-attachments/assets/5e6ea2f6-b9d1-4e97-8ec6-7d4683e926f4">

No region endpoints are enabled, just the default one.

**Comment by sweharris** [comment]
OK, that's a good test and I agree that shows the authn side of things is correct (which is normally the hardest bit).

FWIW, that last option needs to be on so the lamba code can let Alexa know when a button changes state.

The language shouldn't matter 'cos we're not talking to this skill, but it might be  worth verifying it's set to the same as whatever language you have your Echo device set to.  

Grasping at straws... you did define this as a "smart home" skill in the Alexa developer console?

So I have no idea why you're not seeing discovery requests!  That's got me stumped.

**Comment by nickrmb** [comment]
It is defined as a smart home skill:
<img width="1477" alt="image" src="https://github.com/user-attachments/assets/d117de20-4335-483e-89b9-fa756c72777b">

I don't have an echo paired with the account, I therefore only use my mobile device currently, but the app language is set to english and the alexa on the phone is also set to english, the skill as well.

Is there any way I can debug whether the discovery request even reaches the skill in the first place? I feel like the discovery does not discover devices within the skill, even though it is activated.

**Comment by sweharris** [comment]
In the Alexa developer console on the "test" tab there's a bunch of new options that weren't there when I last looked.  You may need to toggle "skill testing is enabled in: development".

I see a "device log" at the top and a "Smart home debugger" toggle.  But I've never used them so let's see what happens.

OK, I turned them on then did "alexa discover new devices" in the text box on the left.  Hmm, that generated some log events (right frame scroll down) but I don't see discovery events there.

So I don't know if there's a way of seeing things from the Alexa side :-(

**Comment by nickrmb** [comment]
<img width="528" alt="image" src="https://github.com/user-attachments/assets/eee42a09-bcc6-4def-bc07-f651ed63ad3c">

Actually for me nothing changes when I say "discover new devices" or try the manual way. Could it be an issue with my alexa app?

**Comment by sweharris** [comment]
Yeah, I think what's happening is the dev console is emulating an Echo device (maybe a "hub") and the log entries we're seeing are for that emulated device, so we'r'e not seeing "backend" events.

If you typed "alexa discover devices" into the text box then it'll do a full discovery.  I can see the blue light on my Echo light up!  

![image](https://github.com/user-attachments/assets/a18378b9-321b-4adc-8cfb-11e29587597c)

And that caused cloudwatch discovery entry to be generated by the lambda.  This isn't using the mobile app, so if that fails for you then it's probably not your phone app.

I've never tried smart home discovery without a physical Echo device.  I assume it'll work as normal, but I dunno!

**Comment by nickrmb** [comment]
What is weird is that when I try this I don't get even get the message that it is starting discovery like you got. Also therefore no log entry was generated as well

**Comment by nickrmb** [comment]
You wrote that the client secret looks like this
0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

but mine looks like this
amzn1.oa2-cs.v1.0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

Should i then discard the "amzn1.oa2-cs." part?

**Comment by nickrmb** [comment]
Also one very weird thing that I observed is that this happens:
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/9ed692c3-c16c-498a-9260-f25853630631">

Even though I successfully linked my account in the app and enabled it. Do you have any idea why this happens? Did I link it with the wrong account?

**Comment by sweharris** [comment]
We saw that exact error in #6 which was caused by deploying to the wrong region.

 I have to wonder if Alexa is behaving weird for you because you don't have any physical devices, just the app.  

Hmm, is your Amazon account associated with amazon.de or .co.uk or .com ?

I don't know if this will make any difference, but try setting the API endpoint to the US one; that can be done with the API command "setendpoint" with the value https://api.amazonalexa.com/v3/event

(or set the DynamoDB entry for 100005 to that value)

Afterwards you could reset to the default by deleting button 100005

If that now lets the notification to be sent then Amazon thinks your Alexa is associated with  US region.

**Comment by nickrmb** [comment]
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/ee100ced-95be-438a-a30f-51009994e840">

Hmm this seems to work with the US api endpoint, but why? Does this mean the skill running on US servers? Could this be why I dont get discover requests?

**Comment by sweharris** [comment]
No, the skill is running in eu region, which is why it picked up the EU endpoint.  But it's possible your _Alexa_ thinks it is in US region!

I don't know if changing this in the app (From the app, select devices, select "Alexa on this phone", settings cog, device location) will change things or not.

It's _possible_ this is what's causing discovery failures as well, but that's just a guess.

**Comment by nickrmb** [comment]
Hmm, device location and time zone was already set to a german one.

I am always on developer.amazon**.com** but there is no developer.amazon.de or developer.amazon.co.uk

**Comment by nickrmb** [comment]
Could it be that the account is associated to be an american account, but the alexa device on the phone is german and hence it does not pick up the "american" devices?

**Comment by sweharris** [comment]
I have a number of guesses (and that's all they are)

* The account is somehow associated with US region
* The Alexa app runs from US region
* No physical Echo devices causes discovery to fail
* All of the above ;-)

I can't test any of these things 'cos I'm in NJ and so everything runs from US region!

**Comment by nickrmb** [comment]
Thanks for the great help, this narrowed it down and I actually found the problem.
It was actually the region which was unset all the time. Probably it defaulted to the US due to that.
I went to the amazon shopping site and set the region there. Then it finally worked, the discover request came in!
Thank you very much for the fast responses, could not have done it without you :).

**Comment by sweharris** [comment]
Nice!  Where did you need to set the region?  Just in case someone else has the same problem :-)

**Comment by sweharris** [comment]
Nice!  I'll remember that in case someone else has the same problem!

**Comment by mikaeldui** [comment]
> Thanks for the great help, this narrowed it down and I actually found the problem. It was actually the region which was unset all the time. Probably it defaulted to the US due to that. I went to the amazon shopping site and set the region there. Then it finally worked, the discover request came in! Thank you very much for the fast responses, could not have done it without you :).

I was changing the regions of my account, and then back to the UK and suddenly everything was reset.

Turns out that even though my Amazon Country/Region was set to the UK I had to "transfer my kindle purchases to Amazon.co.uk" to complete the region change.
